In [ ]:
import pandas as pd 
data = pd.read_csv('./ratings.csv')

# print(type(data))
data.shape
#获取前五行数据
# data.head(10)
#后五行数据
# data.tail()
# data.columns.tolist()
# data.index

# data.dtypes

In [152]:
#csv数据里面存在中文
#utf-8 gbk
#mac 编码方式
# data = pd.read_csv('./ratings_chinses.csv',encoding='gbk')
# data
# #设置读取的编码方式
# #查看csv文件编码格式
import chardet 
data = open('./ratings_chinses.csv','rb')
# #查看csv文件编码格式
#confidence : 下节课查询 #置信度:信心强度
print(chardet.detect(data.readline()))

{'encoding': 'GB2312', 'confidence': 0.99, 'language': 'Chinese'}

In [ ]:
#dataframe 二维表结构 ,Series (一行或者一列)
import pandas as pd
from pandas import Series,DataFrame
import numpy as np

# 创建Series对象并省略索引
'''
index 参数是可省略的，你可以选择不输入这个参数。
如果不带 index 参数，Pandas 会自动用默认 index 进行索引，类似数组，索引值是 [0, ..., len(data) - 1]
'''
sel =  Series([1,2,3,4])
print(sel)

# # 通常我们会自己创建索引
sel =  Series(data = [1,2,3,4], index = ['a','b','c','d'])

sel =  Series(data = [1,2,3,4], index = list('abcd'))
sel

# # 获取内容
print(sel.values)
# # 获取索引
print(sel.index)
# # 获取索引和值对
print(list(sel.iteritems()))

In [ ]:
# 将字典转换为Series
#json数据  

# dict={"red":100,"black":400,"green":300,"pink":900}
# se3=Series(dict)
# print(se3)

# Series数据获取
sel =  Series(data = [1,2,3,4], index = list('abcd'))
result = list('abcd')
print(result)
print(sel)

# # Series对象同时支持位置和标签两种方式获取数据
# print('索引下标',sel['c'])
# print('位置下标',sel[2])

# # # 获取不连续的数据
# print('索引下标',sel[['a','c']])
# print('位置下标',sel[[1,3]])

# # 可以使用切片或取数据
# print('位置切片',sel[1:3])# 左包含右不包含
# print('索引切片',sel['b':'d'])# 左右都包含

# # 重新赋值索引的值
#在原有数据基础上修改
# sel.index = list('dcba')
# print(sel)
# # ReIndex重新索引,会返回一个新的Series(调用reindex将会重新排序，缺失值则用NaN填补)
#查询一下规则
#返回新的数据,不在原有数据修改
# print(sel.reindex(['b','a','c','d','e']))

# # Drop丢弃指定轴上的项()
se1=pd.Series(range(10,15))
print(se1)
print(se1.drop([2,3]))

In [ ]:
# series1 = pd.Series([1,2,3,4],['London','HongKong','Humbai','lagos'])
# series2 = pd.Series([1,3,6,4],['London','Accra','lagos','Delhi'])
# print(series1)
# print(series2)

# # print(series1-series2)
# print(series1+series2)
# print(series1*series2)

# # 同样也支持numpy的数组运算
sel =  Series(data = [1,6,3,5], index = list('abcd'))
sel
print(sel[sel>3]) # 布尔数组过滤
print(sel*2) # 标量乘法
print(np.square(sel))

In [ ]:
# 1. 创建DataFrame
# 使用二维数组
# df1 = DataFrame(np.random.randint(0,10,(4,4)),index=[1,2,3,4],columns=['a','b','c','d'])
# print(df1)

# 使用字典创建(行索引由index决定，列索引由字典的键决定)
# dict={
#     'Province': ['Guangdong', 'Beijing', 'Qinghai', 'Fujian'],
#     'pop': [1.3, 2.5, 1.1, 0.7],
#     'year': [2018, 2018, 2018, 2018]}
# df2=pd.DataFrame(dict)
# print(df2)

# # 使用from_dict
dict2={"a":[1,2,3],"b":[4,5,6]}
df6=pd.DataFrame.from_dict(dict2)
print(df6)

# #索引相同的情况下，相同索引的值会相对应，缺少的值会添加NaN
data = {
    'Name':pd.Series(['zs','ls','we'],index=['a','b','c']),
    'Age':pd.Series(['10','20','30','40'],index=['a','b','c','d']),
    'country':pd.Series(['中国','日本','韩国'],index=['a','c','b'])
}

# df = pd.DataFrame(data)
# print(df)
# # to_dict()方法将DataFrame对象转换为字典
dict = df.to_dict()
print(dict)

In [ ]:
import pandas as pd
from pandas import Series,DataFrame
import numpy as np

# dataframe常用属性
df_dict = {
	'name':['James','Curry','Iversion'],
	'age':['18','20','19'],
	'national':['us','China','us']
}
df = pd.DataFrame(data=df_dict,index=['0','1','2'])
print(df)
# 获取行数和列数
# print(df.shape)

# # # # 获取行索引
# print(df.index.tolist())

# # # # 获取列索引
# print(df.columns.tolist())

# # # 获取数据的类型
# print(df.dtypes)

# # 获取数据的维度
# print(df.ndim)

# # # values属性也会以二维ndarray的形式返回DataFrame的数据
# print(df.values)

# # # 展示df的概览
# print(df.info())

# # # 显示头几行,默认显示5行
# print(df.head(2))

# # # 显示后几行
# print(df.tail(1))

# # 获取DataFrame的列
print(df['name'])
# # #因为我们只获取一列，所以返回的就是一个 Series
print(type(df['name']))

# # # 如果获取多个列，那返回的就是一个 DataFrame 类型：
print(df[['name','age']])

print(type(df[['name','age']]))#

In [83]:
#列表生成式:列表推导式:通俗理解就是使用for循环快速创建一个列表
# my_list = []
# for i in range(1,6):
#     my_list.append(i)
# print(my_list)
#列表生成式的方式创建
# my_list = [value*2 for value in range(1,6)]
# my_list
# # print(my_list)
# #统计每个元素的个数
# my_list = [len(value) for value in ['abc',"ab"]]
# print(my_list)
# my_list = [value+'haha' for value in ['abc',"ab"]]
# my_list
# #双层for循环 
# my_list = [[x,y]for x in range(1,3) for y in range(1,3)]
# my_list
# for x in range(1,3):
#     print(x)
#     for y in range(1,3):
#         print(y)

# #结合 if 语句 
my_list = [value for value in range(1,11)if value % 2 == 0]
print(my_list)

[2, 4, 6, 8, 10]

In [116]:
#此案例必须敲一遍
data = pd.read_csv('./BJ_tianqi.csv')
# print(data)
# data.shape

#获取一列数据
# result = data['日期'] #什么类型 df 1 se2
# result
#获取最高温度
#loc自定索引切片方式
# data.loc[:,'最高温度']
#改变数据的行索引返回一个新的数据
# print(data.set_index('日期'))
#inplace = True在原有数据基础上修改
data.set_index('日期',inplace=True)
data
data.index.name = None
# print(data)
# data.head()
# #将最高温度改变成数字

data.loc[:,'最高温度']=data['最高温度'].str.replace('℃','').astype('int32')
data
# # #将最低温度修改成数字
data.loc[:,'最低温度']=data['最低温度'].str.replace('℃','').astype('int32')
data
# #全年最高温度那一天的信息,ascending=True 升序
result = data.sort_values(by='最高温度',ascending=True)
#进行数据预处理 不满足分析挖掘的条件
result
#获取一行 
#iloc 位置索引
# result = result.iloc[0,:]
# print(result)
#获取某几行数据某几列
#[2019/1/3 1/4/ ]
#自定义索引
# data.head()

data.loc[['2019/1/3','2019/1/4','2019/1/5'],['最高温度','最低温度']]

# data.head()
#最高温度大于30度


result = data.loc[data['最高温度']>32]


result = data.loc[(data['最高温度']<30)&(data['最低温度']>20)]
result
#查询9月的所有数据
# 所有数据取出来 2019/09 startswith
data.head()
# index_list = data.index.tolist()
# # #i.startswith('2019/09' -> TRUE fasle
# result = [i.startswith('2019/9') for i in index_list]

# result = data.loc[result,:]
# result
# #[if i == 2019/9 ->ELSE False for i in index_list]
# #列表生成式[for ]for后面只能写if,不能写else
# #温差一列 
data.loc[:,'温差']=data['最高温度']-data['最低温度']
# data
# #温差>=10 大温差 其他情况小温差 
# #增加新的列温差类型
# data.loc[:,"温差类型"]=['大温差' if value>=10 else '正常' for value in data['温差']]
# data
# # #全年里面有多少天是正常温差
# # data = data.loc[:,'温差类型'].value_counts()

# data = data.loc[:,'风向'].value_counts()
# data
# #默认按照第一个参数排序,再去按照温差排序
data.sort_values(by=['最高温度','温差'],ascending=False)
data.sort_values(by=['最高温度','温差'],ascending=[False,True])

            最高温度  最低温度      天气   风向  风级  空气质量  温差
2019/7/4      38    25    晴~多云  西南风  2级     良  13
2019/7/26     37    27       晴  西南风  2级     良  10
2019/5/23     37    21       晴  东南风  2级     良  16
2019/7/21     36    27    晴~多云  西南风  2级  轻度污染   9
2019/7/24     36    27  多云~雷阵雨  西南风  2级     良   9
...          ...   ...     ...  ...  ..   ...  ..
2019/1/15     -2   -10       晴  西北风  3级     良   8
2019/2/14     -3    -6   小雪~多云  东南风  2级     良   3
2019/2/12     -3    -8   小雪~多云  东北风  2级     优   5
2019/12/31    -3   -10       晴  西北风  1级     优   7
2019/12/30    -5   -12       晴  西北风  4级     优   7

[365 rows x 7 columns]

In [128]:
import pandas as pd 
import numpy as np 
#空值处理
#删除缺失值 dropna 
# filna 填充 
#isnull 
#headers = 2 将第二行作为列索引
#headers = None 避免读取的时候将第一行作为索引
#行索引
#跳跃到索引为2的行上
df = pd.read_excel('./student_excel.xlsx',header=2)
# df 
#如果你想要截取excle的一段范围skiprows
df = pd.read_excel('./student_excel.xlsx',skiprows=2,usecols="B:E")
df 
# #删除全是空值的列
# #how,= any只要有空值就删除 all 全是空值删除
df.dropna(axis=0,how='all',inplace=True)
print(df)
# # #
# df.dropna(axis=0,how='any',inplace=True)
# df
# #填充的方式
# #分数参数是列索引
df.fillna({'姓名':"无名氏"},inplace=True)
df

     姓名  科目    分数
0    小明  语文  85.0
1   NaN  数学  80.0
2   NaN  英语  90.0
4    小王  语文  85.0
5   NaN  数学   NaN
6   NaN  英语  90.0
8    小刚  语文  85.0
9   NaN  数学  80.0
10  NaN  英语  90.0

     姓名  科目    分数
0    小明  语文  85.0
1   NaN  数学  80.0
2   NaN  英语  90.0
4    小王  语文  85.0
5   NaN  数学   0.0
6   NaN  英语  90.0
8    小刚  语文  85.0
9   NaN  数学  80.0
10  NaN  英语  90.0

In [131]:
# axix 
#0删除的是列 1 代表的是行
df = pd.DataFrame(np.arange(12).reshape(3,4),columns=['A','B','C','D'])
df
#1获取到所有行的A列删除它
# df = df.drop('A',axis=1)
df
# # 获取所有的列的第一行 1
# #获取所有行的第一列 2
#提示一下:尽量不要删除数据源
df = df.drop(1,axis=0)
df

   A  B   C   D
0  0  1   2   3
2  8  9  10  11

In [151]:
# 使用join合并，着重关注的是行的合并
import pandas as pd
df3=pd.DataFrame({'Red':[1,3,5],'Green':[5,0,3]},index=list('abc'))
df4=pd.DataFrame({'Blue':[1,9,8],'Yellow':[6,6,7]},index=list('cde'))
print(df3)
print(df4)

# # 简单合并（默认是left左连接,以左侧df3为基础）
# df3.join(df4,how='left')

# # 右链接
df3.join(df4,how='right')

# # # 外链接
# df3.join(df4,how='outer')

# # # 合并多个DataFrame对象
# df5=pd.DataFrame({'Brown':[3,4,5],'White':[1,1,2]},index=list('aed'))
# df5
#课下练习尝试多个表 使用右链接的方式 
#为什么告知我
# df3.join([df4,df5],how='right')

   Red  Green
a    1      5
b    3      0
c    5      3
   Blue  Yellow
c     1       6
d     9       6
e     8       7

   Red  Green  Blue  Yellow
c  5.0    3.0     1       6
d  NaN    NaN     9       6
e  NaN    NaN     8       7

In [149]:
# 使用merge，着重关注的是列的合并
df1=pd.DataFrame({'名字':list('ABCDE'),'性别':['男','女','男','男','女'],'职称':['副教授','讲师','助教','教授','助教']},index=range(1001,1006))
# df1.columns.name='学院老师'
# df1.index.name='编号'
print(df1)

df2=pd.DataFrame({'名字':list('ABDAX'),'课程':['C++','计算机导论','汇编','数据结构','马克思原理'],'职称':['副教授','讲师','教授','副教授','讲师']},index=[1001,1002,1004,1001,3001])
# df2.columns.name='课程'
# df2.index.name='编号'
print(df2)

# # 默认下是根据左右对象中出现同名的列作为连接的键，且连接方式是how=’inner’
#返回新的数据
# print(pd.merge(df1,df2))# 返回匹配的

# # 指定列名合并
# pd.merge(df1,df2,on='名字',suffixes=['_1','_2'])# 返回匹配的

# # 连接方式，根据左侧为准
# pd.merge(df1,df2,how='left')


# # 根据右侧为准
# pd.merge(df1,df2,how='right')

# # 所有
# pd.merge(df1,df2,how='outer')

# # 根据多个键进行连接
pd.merge(df1,df2,on=['职称','名字'])

     名字 性别   职称
1001  A  男  副教授
1002  B  女   讲师
1003  C  男   助教
1004  D  男   教授
1005  E  女   助教
     名字     课程   职称
1001  A    C++  副教授
1002  B  计算机导论   讲师
1004  D     汇编   教授
1001  A   数据结构  副教授
3001  X  马克思原理   讲师

  名字 性别   职称     课程
0  A  男  副教授    C++
1  A  男  副教授   数据结构
2  B  女   讲师  计算机导论
3  D  男   教授     汇编