In [1]:
import pandas as pd
import numpy as np

In [2]:
docAddress = r"C:\Users\MaleBird\Desktop\【大数据文件1】huodianhour2019_v4.csv"

In [4]:
df = pd.read_csv(docAddress,engine='python')

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1911687 entries, 0 to 1911686
Data columns (total 15 columns):
 #   Column             Dtype
---  ------             -----
 0   pscode             int64
 1   outputcode         int64
 2   pollutant_code     int64
 3   psname             object
 4   outputname         object
 5   PollutantName      object
 6   data_time          object
 7   RevisedStrength    float64
 8   RevisedzsStrength  float64
 9   RevisedFlow        float64
 10  flow               float64
 11  VALUES01           float64
 12  VALUES03           float64
 13  VALUES05           float64
 14  StandardValue      int64
dtypes: float64(7), int64(4), object(4)
memory usage: 218.8+ MB

In [6]:
df.head()

,pscode,outputcode,pollutant_code,psname,outputname,PollutantName,data_time,RevisedStrength,RevisedzsStrength,RevisedFlow,flow,VALUES01,VALUES03,VALUES05,StandardValue
0,640000000005,201,3,华电宁夏灵武发电有限公司,脱硫出口1,氮氧化物,2019-07-11 05:00:00,41.041,38.722,79.93,1947449.50,5.100,52.287,6.634,100
1,640000000005,201,3,华电宁夏灵武发电有限公司,脱硫出口1,氮氧化物,2019-07-11 06:00:00,44.454,42.167,86.62,1948522.87,5.185,51.953,6.634,100
2,640000000005,201,3,华电宁夏灵武发电有限公司,脱硫出口1,氮氧化物,2019-07-11 07:00:00,47.266,45.024,90.04,1904971.12,5.254,51.909,9.076,100
3,640000000005,201,3,华电宁夏灵武发电有限公司,脱硫出口1,氮氧化物,2019-07-11 08:00:00,40.486,39.561,73.05,1804418.87,5.726,51.816,10.911,100
4,640000000005,201,3,华电宁夏灵武发电有限公司,脱硫出口1,氮氧化物,2019-07-11 09:00:00,33.393,35.648,51.38,1538769.62,6.939,51.071,10.889,100

In [7]:
df.nunique()

pscode                   49
outputcode               40
pollutant_code            3
psname                   49
outputname               88
PollutantName             3
data_time              8760
RevisedStrength      159345
RevisedzsStrength    188052
RevisedFlow          128966
flow                 597860
VALUES01              34134
VALUES03              74230
VALUES05              39109
StandardValue             9
dtype: int64

In [8]:
df.columns('pscode','OutputCode','PollutantCode','psname','PollutantName','MonitorTime','RevisedStrength','RzsStrength','RevisedFlow','cou','S01','S03','S05','StandardValue')

TypeError: 'Index' object is not callable

In [9]:
list(df)

['pscode',
 'outputcode',
 'pollutant_code',
 'psname',
 'outputname',
 'PollutantName',
 'data_time',
 'RevisedStrength',
 'RevisedzsStrength',
 'RevisedFlow',
 'flow',
 'VALUES01',
 'VALUES03',
 'VALUES05',
 'StandardValue']

In [11]:
df.rename(columns={'outputcode':'OutputCode'})

,pscode,OutputCode,pollutant_code,psname,outputname,PollutantName,data_time,RevisedStrength,RevisedzsStrength,RevisedFlow,flow,VALUES01,VALUES03,VALUES05,StandardValue
0,640000000005,201,3,华电宁夏灵武发电有限公司,脱硫出口1,氮氧化物,2019-07-11 05:00:00,41.041,38.722,79.93,1947449.50,5.100,52.287,6.634,100
1,640000000005,201,3,华电宁夏灵武发电有限公司,脱硫出口1,氮氧化物,2019-07-11 06:00:00,44.454,42.167,86.62,1948522.87,5.185,51.953,6.634,100
2,640000000005,201,3,华电宁夏灵武发电有限公司,脱硫出口1,氮氧化物,2019-07-11 07:00:00,47.266,45.024,90.04,1904971.12,5.254,51.909,9.076,100
3,640000000005,201,3,华电宁夏灵武发电有限公司,脱硫出口1,氮氧化物,2019-07-11 08:00:00,40.486,39.561,73.05,1804418.87,5.726,51.816,10.911,100
4,640000000005,201,3,华电宁夏灵武发电有限公司,脱硫出口1,氮氧化物,2019-07-11 09:00:00,33.393,35.648,51.38,1538769.62,6.939,51.071,10.889,100
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1911682,640000000005,201,3,华电宁夏灵武发电有限公司,脱硫出口1,氮氧化物,2019-07-11 00:00:00,43.972,41.075,81.10,1844341.25,4.937,52.271,11.345,100
1911683,640000000005,201,3,华电宁夏灵武发电有限公司,脱硫出口1,氮氧化物,2019-07-11 01:00:00,38.058,35.512,73.31,1926318.37,4.892,52.325,7.099,100
1911684,640000000005,201,3,华电宁夏灵武发电有限公司,脱硫出口1,氮氧化物,2019-07-11 02:00:00,42.692,39.615,81.99,1920541.50,4.833,52.166,6.634,100
1911685,640000000005,201,3,华电宁夏灵武发电有限公司,脱硫出口1,氮氧化物,2019-07-11 03:00:00,43.130,40.555,83.76,1942136.62,5.041,52.051,6.634,100
1911686,640000000005,201,3,华电宁夏灵武发电有限公司,脱硫出口1,氮氧化物,2019-07-11 04:00:00,44.277,41.686,86.34,1949970.50,5.068,52.415,6.634,100

In [12]:
df.rename(columns={'pollutant_code':'PollutantCode','outputname':'OutputName','data_time':'MonitorTime'})

,pscode,outputcode,PollutantCode,psname,OutputName,PollutantName,MonitorTime,RevisedStrength,RevisedzsStrength,RevisedFlow,flow,VALUES01,VALUES03,VALUES05,StandardValue
0,640000000005,201,3,华电宁夏灵武发电有限公司,脱硫出口1,氮氧化物,2019-07-11 05:00:00,41.041,38.722,79.93,1947449.50,5.100,52.287,6.634,100
1,640000000005,201,3,华电宁夏灵武发电有限公司,脱硫出口1,氮氧化物,2019-07-11 06:00:00,44.454,42.167,86.62,1948522.87,5.185,51.953,6.634,100
2,640000000005,201,3,华电宁夏灵武发电有限公司,脱硫出口1,氮氧化物,2019-07-11 07:00:00,47.266,45.024,90.04,1904971.12,5.254,51.909,9.076,100
3,640000000005,201,3,华电宁夏灵武发电有限公司,脱硫出口1,氮氧化物,2019-07-11 08:00:00,40.486,39.561,73.05,1804418.87,5.726,51.816,10.911,100
4,640000000005,201,3,华电宁夏灵武发电有限公司,脱硫出口1,氮氧化物,2019-07-11 09:00:00,33.393,35.648,51.38,1538769.62,6.939,51.071,10.889,100
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1911682,640000000005,201,3,华电宁夏灵武发电有限公司,脱硫出口1,氮氧化物,2019-07-11 00:00:00,43.972,41.075,81.10,1844341.25,4.937,52.271,11.345,100
1911683,640000000005,201,3,华电宁夏灵武发电有限公司,脱硫出口1,氮氧化物,2019-07-11 01:00:00,38.058,35.512,73.31,1926318.37,4.892,52.325,7.099,100
1911684,640000000005,201,3,华电宁夏灵武发电有限公司,脱硫出口1,氮氧化物,2019-07-11 02:00:00,42.692,39.615,81.99,1920541.50,4.833,52.166,6.634,100
1911685,640000000005,201,3,华电宁夏灵武发电有限公司,脱硫出口1,氮氧化物,2019-07-11 03:00:00,43.130,40.555,83.76,1942136.62,5.041,52.051,6.634,100
1911686,640000000005,201,3,华电宁夏灵武发电有限公司,脱硫出口1,氮氧化物,2019-07-11 04:00:00,44.277,41.686,86.34,1949970.50,5.068,52.415,6.634,100

In [13]:
df.rename(columns={'RevisedzsStrength':'RzsStrength','flow':'cou','VALUES01':'S01','VALUES02':'S02','VALUES03':'S03'})

,pscode,outputcode,pollutant_code,psname,outputname,PollutantName,data_time,RevisedStrength,RzsStrength,RevisedFlow,cou,S01,S03,VALUES05,StandardValue
0,640000000005,201,3,华电宁夏灵武发电有限公司,脱硫出口1,氮氧化物,2019-07-11 05:00:00,41.041,38.722,79.93,1947449.50,5.100,52.287,6.634,100
1,640000000005,201,3,华电宁夏灵武发电有限公司,脱硫出口1,氮氧化物,2019-07-11 06:00:00,44.454,42.167,86.62,1948522.87,5.185,51.953,6.634,100
2,640000000005,201,3,华电宁夏灵武发电有限公司,脱硫出口1,氮氧化物,2019-07-11 07:00:00,47.266,45.024,90.04,1904971.12,5.254,51.909,9.076,100
3,640000000005,201,3,华电宁夏灵武发电有限公司,脱硫出口1,氮氧化物,2019-07-11 08:00:00,40.486,39.561,73.05,1804418.87,5.726,51.816,10.911,100
4,640000000005,201,3,华电宁夏灵武发电有限公司,脱硫出口1,氮氧化物,2019-07-11 09:00:00,33.393,35.648,51.38,1538769.62,6.939,51.071,10.889,100
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1911682,640000000005,201,3,华电宁夏灵武发电有限公司,脱硫出口1,氮氧化物,2019-07-11 00:00:00,43.972,41.075,81.10,1844341.25,4.937,52.271,11.345,100
1911683,640000000005,201,3,华电宁夏灵武发电有限公司,脱硫出口1,氮氧化物,2019-07-11 01:00:00,38.058,35.512,73.31,1926318.37,4.892,52.325,7.099,100
1911684,640000000005,201,3,华电宁夏灵武发电有限公司,脱硫出口1,氮氧化物,2019-07-11 02:00:00,42.692,39.615,81.99,1920541.50,4.833,52.166,6.634,100
1911685,640000000005,201,3,华电宁夏灵武发电有限公司,脱硫出口1,氮氧化物,2019-07-11 03:00:00,43.130,40.555,83.76,1942136.62,5.041,52.051,6.634,100
1911686,640000000005,201,3,华电宁夏灵武发电有限公司,脱硫出口1,氮氧化物,2019-07-11 04:00:00,44.277,41.686,86.34,1949970.50,5.068,52.415,6.634,100

In [14]:
df.rename(columns={'VALUES05':'S05'})

,pscode,outputcode,pollutant_code,psname,outputname,PollutantName,data_time,RevisedStrength,RevisedzsStrength,RevisedFlow,flow,VALUES01,VALUES03,S05,StandardValue
0,640000000005,201,3,华电宁夏灵武发电有限公司,脱硫出口1,氮氧化物,2019-07-11 05:00:00,41.041,38.722,79.93,1947449.50,5.100,52.287,6.634,100
1,640000000005,201,3,华电宁夏灵武发电有限公司,脱硫出口1,氮氧化物,2019-07-11 06:00:00,44.454,42.167,86.62,1948522.87,5.185,51.953,6.634,100
2,640000000005,201,3,华电宁夏灵武发电有限公司,脱硫出口1,氮氧化物,2019-07-11 07:00:00,47.266,45.024,90.04,1904971.12,5.254,51.909,9.076,100
3,640000000005,201,3,华电宁夏灵武发电有限公司,脱硫出口1,氮氧化物,2019-07-11 08:00:00,40.486,39.561,73.05,1804418.87,5.726,51.816,10.911,100
4,640000000005,201,3,华电宁夏灵武发电有限公司,脱硫出口1,氮氧化物,2019-07-11 09:00:00,33.393,35.648,51.38,1538769.62,6.939,51.071,10.889,100
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1911682,640000000005,201,3,华电宁夏灵武发电有限公司,脱硫出口1,氮氧化物,2019-07-11 00:00:00,43.972,41.075,81.10,1844341.25,4.937,52.271,11.345,100
1911683,640000000005,201,3,华电宁夏灵武发电有限公司,脱硫出口1,氮氧化物,2019-07-11 01:00:00,38.058,35.512,73.31,1926318.37,4.892,52.325,7.099,100
1911684,640000000005,201,3,华电宁夏灵武发电有限公司,脱硫出口1,氮氧化物,2019-07-11 02:00:00,42.692,39.615,81.99,1920541.50,4.833,52.166,6.634,100
1911685,640000000005,201,3,华电宁夏灵武发电有限公司,脱硫出口1,氮氧化物,2019-07-11 03:00:00,43.130,40.555,83.76,1942136.62,5.041,52.051,6.634,100
1911686,640000000005,201,3,华电宁夏灵武发电有限公司,脱硫出口1,氮氧化物,2019-07-11 04:00:00,44.277,41.686,86.34,1949970.50,5.068,52.415,6.634,100

In [15]:
df.head()

,pscode,outputcode,pollutant_code,psname,outputname,PollutantName,data_time,RevisedStrength,RevisedzsStrength,RevisedFlow,flow,VALUES01,VALUES03,VALUES05,StandardValue
0,640000000005,201,3,华电宁夏灵武发电有限公司,脱硫出口1,氮氧化物,2019-07-11 05:00:00,41.041,38.722,79.93,1947449.50,5.100,52.287,6.634,100
1,640000000005,201,3,华电宁夏灵武发电有限公司,脱硫出口1,氮氧化物,2019-07-11 06:00:00,44.454,42.167,86.62,1948522.87,5.185,51.953,6.634,100
2,640000000005,201,3,华电宁夏灵武发电有限公司,脱硫出口1,氮氧化物,2019-07-11 07:00:00,47.266,45.024,90.04,1904971.12,5.254,51.909,9.076,100
3,640000000005,201,3,华电宁夏灵武发电有限公司,脱硫出口1,氮氧化物,2019-07-11 08:00:00,40.486,39.561,73.05,1804418.87,5.726,51.816,10.911,100
4,640000000005,201,3,华电宁夏灵武发电有限公司,脱硫出口1,氮氧化物,2019-07-11 09:00:00,33.393,35.648,51.38,1538769.62,6.939,51.071,10.889,100

In [17]:
df2 = df.rename(columns={'outputcode':'OutputCode','pollutant_code':'PollutantCode','outputname':'OutputName','data_time':'MonitorTime','RevisedzsStrength':'RzsStrength','flow':'cou','VALUES01':'S01','VALUES03':'S03','VALUES05':'S05'})

In [18]:
df2.to_csv('huodianhour2019_v4-2.csv', index=False)

In [19]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1911687 entries, 0 to 1911686
Data columns (total 15 columns):
 #   Column           Dtype
---  ------           -----
 0   pscode           int64
 1   OutputCode       int64
 2   PollutantCode    int64
 3   psname           object
 4   OutputName       object
 5   PollutantName    object
 6   MonitorTime      object
 7   RevisedStrength  float64
 8   RzsStrength      float64
 9   RevisedFlow      float64
 10  cou              float64
 11  S01              float64
 12  S03              float64
 13  S05              float64
 14  StandardValue    int64
dtypes: float64(7), int64(4), object(4)
memory usage: 218.8+ MB

In [2]:
docAddress = r"C:\Users\MaleBird\Desktop\火电行业2019年数据\huodian2019_v4.csv"
df = pd.read_csv(docAddress,engine='python') 
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 78262 entries, 0 to 78261
Data columns (total 15 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   pscode             78262 non-null  int64
 1   outputcode         78262 non-null  int64
 2   pollutant_code     78262 non-null  int64
 3   psname             78262 non-null  object
 4   outputname         78262 non-null  object
 5   PollutantName      78262 non-null  object
 6   data_time          78262 non-null  object
 7   RevisedStrength    78262 non-null  float64
 8   RevisedzsStrength  77423 non-null  float64
 9   RevisedFlow        78262 non-null  float64
 10  flow               78262 non-null  float64
 11  VALUES01           78262 non-null  float64
 12  VALUES03           78262 non-null  float64
 13  VALUES05           74596 non-null  float64
 14  StandardValue      78262 non-null  int64
dtypes: float64(7), int64(4), object(4)
memory usage: 9.0+ MB

In [3]:
df.head()

,pscode,outputcode,pollutant_code,psname,outputname,PollutantName,data_time,RevisedStrength,RevisedzsStrength,RevisedFlow,flow,VALUES01,VALUES03,VALUES05,StandardValue
0,620000000094,2,3,大唐甘肃发电有限公司八零三热电厂,1号机组脱硫出口,氮氧化物,2019-09-06 00:00:00,5.598,7.556,19.391,3226244.75,18.8,27.2,14.8,100
1,620000000094,2,2,大唐甘肃发电有限公司八零三热电厂,1号机组脱硫出口,二氧化硫,2019-09-06 00:00:00,0.000,-0.200,0.000,3226244.75,18.8,27.2,14.8,200
2,620000000094,2,1,大唐甘肃发电有限公司八零三热电厂,1号机组脱硫出口,烟尘,2019-09-06 00:00:00,2.470,-8.750,7.980,3226244.75,18.8,27.2,14.8,30
3,620000000094,2,3,大唐甘肃发电有限公司八零三热电厂,1号机组脱硫出口,氮氧化物,2019-09-11 00:00:00,116.123,357.576,897.988,7024851.50,17.0,31.5,17.0,100
4,620000000094,2,2,大唐甘肃发电有限公司八零三热电厂,1号机组脱硫出口,二氧化硫,2019-09-11 00:00:00,0.000,0.000,0.000,7024851.50,17.0,31.5,17.0,200

In [5]:
df.nunique()

pscode                  49
outputcode              40
pollutant_code           3
psname                  49
outputname              88
PollutantName            3
data_time              365
RevisedStrength      34106
RevisedzsStrength    39108
RevisedFlow          57811
flow                 24954
VALUES01              9272
VALUES03             13729
VALUES05             12287
StandardValue            9
dtype: int64

In [6]:
df2 = df.rename(columns={'outputcode':'OutputCode','pollutant_code':'PollutantCode','outputname':'OutputName','data_time':'MonitorTime','RevisedzsStrength':'RzsStrength','flow':'cou','VALUES01':'S01','VALUES03':'S03','VALUES05':'S05'})

In [7]:
df2.to_csv('huodian2019_v4-2.csv', index=False)